"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// Auto-generated by Zenith — edit as needed
exports.default = {
    framework: 'Unknown',
    devServerUrl: 'http://127.0.0.1:8080',
    tsConfigPath: 'c:/Users/Asus/Desktop/ve/zenith-extension/tsconfig.json',
    tailwindConfig: null,
};
//# sourceMappingURL=zenith.config.js.map