// Auto-generated by Zenith — edit as needed
export default {
    framework: 'Vite',
    devServerUrl: 'http://localhost:3001',
    tsConfigPath: 'c:/Users/Asus/Desktop/ve/zenith-extension/webview-ui/tsconfig.json',
    tailwindConfig: 'c:/Users/Asus/Desktop/ve/zenith-extension/webview-ui/tailwind.config.js',
};
