"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.useAppStateManager = exports.useEditorEngine = exports.useUserManager = exports.useUpdateManager = exports.useProjectsManager = exports.useRouteManager = exports.useAuthManager = void 0;
const auth_1 = require("@/lib/auth");
const engine_1 = require("@/lib/editor/engine");
const projects_1 = require("@/lib/projects");
const routes_1 = require("@/lib/routes");
const state_1 = require("@/lib/state");
const update_1 = require("@/lib/update");
const user_1 = require("@/lib/user");
const react_1 = require("react");
const authManager = new auth_1.AuthManager();
const routeManager = new routes_1.RouteManager();
const projectsManager = new projects_1.ProjectsManager();
const updateManager = new update_1.UpdateManager();
const userManager = new user_1.UserManager();
const editorEngine = new engine_1.EditorEngine(projectsManager, userManager);
const appStateManager = new state_1.AppStateManager();
projectsManager.editorEngine = editorEngine;
const AuthContext = (0, react_1.createContext)(authManager);
const RouteContext = (0, react_1.createContext)(routeManager);
const ProjectsContext = (0, react_1.createContext)(projectsManager);
const UpdateContext = (0, react_1.createContext)(updateManager);
const UserContext = (0, react_1.createContext)(userManager);
const EditorEngineContext = (0, react_1.createContext)(editorEngine);
const AppStateContext = (0, react_1.createContext)(appStateManager);
const useAuthManager = () => (0, react_1.useContext)(AuthContext);
exports.useAuthManager = useAuthManager;
const useRouteManager = () => (0, react_1.useContext)(RouteContext);
exports.useRouteManager = useRouteManager;
const useProjectsManager = () => (0, react_1.useContext)(ProjectsContext);
exports.useProjectsManager = useProjectsManager;
const useUpdateManager = () => (0, react_1.useContext)(UpdateContext);
exports.useUpdateManager = useUpdateManager;
const useUserManager = () => (0, react_1.useContext)(UserContext);
exports.useUserManager = useUserManager;
const useEditorEngine = () => (0, react_1.useContext)(EditorEngineContext);
exports.useEditorEngine = useEditorEngine;
const useAppStateManager = () => (0, react_1.useContext)(AppStateContext);
exports.useAppStateManager = useAppStateManager;
//# sourceMappingURL=index.js.map